SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `project` ;
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

CREATE TABLE IF NOT EXISTS `project`.`brand`(
	`BRAND_NAME` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`BRAND_NAME`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `project`.`complaint`(
	`COMPLAINT_ID` DECIMAL(10,0) NOT NULL,
	`STATUS` DECIMAL(1,0) NOT NULL,
    `COMPLAINT_DATE` DATE NOT NULL,
    `RESOLUTION_DATE` DATE,
    `USER_ID` DECIMAL(10,0) NOT NULL,
    `BRAND_NAME` VARCHAR(25) NOT NULL,
	PRIMARY KEY (`COMPLAINT_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `project`.`user`(`USER_ID`),
    FOREIGN KEY (`BRAND_NAME`) REFERENCES `project`.`brand`(`BRAND_NAME`),
    CHECK (`RESOLUTION_DATE` IS NULL OR `RESOLUTION_DATE`>`COMPLAINT_DATE`),
    CHECK ((`STATUS` = 1 AND `RESOLUTION_DATE` IS NOT NULL) OR 
           (`STATUS` = 0 AND `RESOLUTION_DATE` IS NULL)))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `project`.`product`(
	`PRODUCT_NAME` VARCHAR(100) NOT NULL,
	`INVENTORY` DECIMAL(5,0) NOT NULL,
    `PRICE` DECIMAL(5,2) NOT NULL,
    `CATEGORY` VARCHAR(25),
    `BRAND_NAME` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`PRODUCT_NAME`),
    FOREIGN KEY (`BRAND_NAME`) REFERENCES `project`.`brand`(`BRAND_NAME`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `project`.`user`(
	`USER_ID` DECIMAL(10,0) NOT NULL,
	`USER_NAME` VARCHAR(25) NOT NULL,
    `USER_AGE` DECIMAL(2,0),
	PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `project`.`orders`(
	`ORDER_ID` DECIMAL(10,0) NOT NULL,
	`ITEM_PRICE` DECIMAL(5,2) NOT NULL,
    `ITEM_QUANTITY` DECIMAL(5,0) NOT NULL,
    `SHIPPING_ADDRESS` VARCHAR(100) NOT NULL,
    `TOTAL_SHIPPING_COST` DECIMAL(5,2) NOT NULL,
    `TOTAL_COST` DECIMAL(10,2) NOT NULL,
    `TIMESTAMP` DATE NOT NULL,
    `PRODUCT_NAME` VARCHAR(100) NOT NULL,
    `USER_ID` DECIMAL(10,0) NOT NULL,
	PRIMARY KEY (`ORDER_ID`),
    FOREIGN KEY (`PRODUCT_NAME`) REFERENCES `project`.`product`(`PRODUCT_NAME`),
    FOREIGN KEY (`USER_ID`) REFERENCES `project`.`user`(`USER_ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `project`.`skin`(
    `SKIN_TYPE` VARCHAR(10) NOT NULL,
	PRIMARY KEY (`SKIN_TYPE`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `project`.`applicability`(
    `SKIN_TYPE` VARCHAR(10) NOT NULL,
    `PRODUCT_NAME` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`SKIN_TYPE`, `PRODUCT_NAME`),
    FOREIGN KEY (`SKIN_TYPE`) REFERENCES `project`.`skin`(`SKIN_TYPE`),
    FOREIGN KEY (`PRODUCT_NAME`) REFERENCES `project`.`product`(`PRODUCT_NAME`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `project`.`review`(
	`PRODUCT_NAME` VARCHAR(100) NOT NULL,
    `USER_ID` DECIMAL(10,0) NOT NULL,
	`RATINGS` DECIMAL(1,1) NOT NULL,
	`COMMENT` VARCHAR(500),
    `REVIEW_DATE` DATE NOT NULL,
	PRIMARY KEY (`PRODUCT_NAME`,`USER_ID`),
    FOREIGN KEY (`PRODUCT_NAME`) REFERENCES `project`.`product`(`PRODUCT_NAME`),
    FOREIGN KEY (`USER_ID`) REFERENCES `project`.`user`(`USER_ID`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
