-- #1
SELECT PRODUCT_NAME 
FROM `project`.`product` 
WHERE CATEGORY = 'Moisturizers';

-- #2
SELECT ORDER_ID
FROM `project`.`orders` AS O, `project`.`user` AS U
WHERE O.USER_ID = U.USER_ID AND U.USER_ID = 'XX';

-- #3
SELECT SUM(O.ITEM_PRICE*O.ITEM_QUANTITY) AS REVENUE
FROM `project`.`orders` AS O, `project`.`product` AS P
WHERE O.PRODUCT_NAME = P.PRODUCT_NAME AND 
	  P.BRAND_NAME = 'LA MER' AND
	  O.TIMESTAMP BETWEEN DATE('2023-03-01') AND DATE('2023-03-31');
      
-- #4
SELECT AVG(RATINGS) AS AVG_RATINGS
FROM `project`.`review`
WHERE PRODUCT_NAME = 'Crème de la Mer';

-- #5
SELECT PRODUCT_NAME
FROM `project`.`review`
GROUP BY PRODUCT_NAME
HAVING AVG(RATINGS) >= 4;

-- #6
SELECT DISTINCT BRAND_NAME
FROM `project`.`complaint`;

-- #7
SELECT ORDER_ID
FROM `project`.`orders` AS O
WHERE O.TIMESTAMP BETWEEN DATE('2023-04-01') AND DATE('2023-04-30');

-- #8
SELECT SUM(ITEM_PRICE*ITEM_QUANTITY) AS REVENUE
FROM `project`.`orders`
WHERE PRODUCT_NAME = 'Crème de la Mer';

-- #9
SELECT COUNT(PRODUCT_NAME)/COUNT(DISTINCT BRAND_NAME) AS AVG_NUM
FROM `project`.`product`;

-- #10
SELECT PRODUCT_NAME
FROM `project`.`orders`
GROUP BY PRODUCT_NAME
HAVING COUNT(*) = (SELECT COUNT(*)
	FROM `project`.`orders`
	GROUP BY PRODUCT_NAME
	ORDER BY COUNT(*) DESC
	LIMIT 1);

-- #11
SELECT PRODUCT_NAME
FROM `project`.`review`
WHERE RATINGS = (SELECT RATINGS
	FROM `project`.`review`
	ORDER BY RATINGS DESC
	LIMIT 1);
    
-- #12
SELECT COUNT(DISTINCT USER_ID) AS NUM_OF_USERS
FROM `project`.`orders` AS O
WHERE O.TIMESTAMP BETWEEN DATE('2022-01-01') AND DATE('2021-12-31');

-- #13
SELECT DISTINCT BRAND_NAME
FROM `project`.`product`
WHERE PRICE > 100;

-- #14
SELECT COUNT(*) AS NUM_OF_REVIEWS
FROM `project`.`review`
GROUP BY PRODUCT_NAME
HAVING PRODUCT_NAME = 'Crème de la Mer';

-- #15
SELECT SUM(O.ITEM_PRICE*O.ITEM_QUANTITY) AS REVENUE
FROM `project`.`orders` AS O, `project`.`user` AS U
WHERE O.USER_ID = U.USER_ID AND
	  U.USER_NAME = 'XX';
      
-- #16
SELECT P.BRAND_NAME AS BRANDS
FROM `project`.`product` AS P, `project`.`review` AS R
WHERE P.PRODUCT_NAME = R.PRODUCT_NAME
GROUP BY P.BRAND_NAME
HAVING AVG(R.RATINGS) >= 4