SET SQL_SAFE_UPDATES = 0;

DELETE FROM `project`.`orders`;
DELETE FROM `project`.`review`;
DELETE FROM `project`.`applicability`;
DELETE FROM `project`.`product`;
DELETE FROM `project`.`complaint`;
DELETE FROM `project`.`skin`;
DELETE FROM `project`.`brand`;
DELETE FROM `project`.`user`;


LOAD DATA INFILE 'E:/Programming/Code_sql/CSC3170/Project/v2/data/skin.csv'
INTO TABLE `project`.`skin`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(SKIN_TYPE);

LOAD DATA INFILE 'E:/Programming/Code_sql/CSC3170/Project/v2/data/brand.csv'
INTO TABLE `project`.`brand`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(BRAND_NAME);

LOAD DATA INFILE 'E:/Programming/Code_sql/CSC3170/Project/v2/data/user.csv'
INTO TABLE `project`.`user`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(USER_ID,USER_NAME,AGE);

LOAD DATA INFILE 'E:/Programming/Code_sql/CSC3170/Project/v2/data/complaint.csv'
INTO TABLE `project`.`complaint`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(COMPLAINT_ID,STATUS,COMPLAINT_DATE,@RESOLUTION_DATE,USER_ID,BRAND_NAME)
SET RESOLUTION_DATE = IF(@RESOLUTION_DATE='', NULL, @RESOLUTION_DATE);

LOAD DATA INFILE 'E:/Programming/Code_sql/CSC3170/Project/v2/data/product.csv'
INTO TABLE `project`.`product`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(PRODUCT_ID,INVENTORY,PRODUCT_NAME,PRICE,CATEGORY,BRAND_NAME);

LOAD DATA INFILE 'E:/Programming/Code_sql/CSC3170/Project/v2/data/applicability.csv'
INTO TABLE `project`.`applicability`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(PRODUCT_ID,SKIN_TYPE);

LOAD DATA INFILE 'E:/Programming/Code_sql/CSC3170/Project/v2/data/order.csv'
INTO TABLE `project`.`orders`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ORDER_ID,ITEM_PRICE,ITEM_QUANTITY,SHIPPING_ADDRESS,TOTAL_SHIPPING_COST,@TOTAL_COST,TIMESTAMP,PRODUCT_ID,USER_ID)
SET TOTAL_COST = ROUND(@TOTAL_COST, 2);

LOAD DATA INFILE 'E:/Programming/Code_sql/CSC3170/Project/v2/data/review.csv'
INTO TABLE `project`.`review`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(USER_ID,PRODUCT_ID,RATINGS,COMMENT,REVIEW_DATE);